### ISSUE TITLE
Question on untargeted attack

### ISSUE THREAD

**Issue by drillermoon** [labsix/limited-blackbox-attacks#7]
Hi.

I set target-class=-1 to run an untargeted attack(in query-limited setting). However, I found that the tensor eval_percent_adv is always False, since there is no line that changes the variable target_class to a nonnegative number.
```eval_percent_adv = tf.equal(eval_preds[0], tf.constant(target_class, tf.int64))```

Thanks.

**Comment by anishathalye** [comment]
We only evaluated targeted attacks in our paper. Looks like this was a bug introduced when we refactored our code for open-sourcing. This can be fixed by setting the target_class to the true class and negating the optimization objective.

We'll try to fix this soon. In the meantime, if you do go ahead and fix it, pull requests are appreciated :)

**Comment by anishathalye** [comment]
Fixed in 75874a82ef90524324e87260baefad4389d9f75f. Thanks for pointing this out.
